name: ESP32 Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - run: |
          arduino-cli core update-index --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
          arduino-cli core install esp32:esp32@1.0.5 --additional-urls https://dl.espressif.com/dl/package_esp32_index.json
      - name: Install libraries
        run: |
          arduino-cli lib install --git-url https://github.com/DouglasBgs/ESP32CamLib.git
          arduino-cli lib install "TinyGPSPlus@1.0.3"
          arduino-cli lib install "ArduinoJson@6.19.4"
          arduino-cli lib install "PubSubClient@2.8.0"
          arduino-cli lib install "Functional-Vlpp@1.0.2"
          ls /home/runner/Arduino/libraries/
      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:nodemcu-32s ./esp32 
          arduino-cli compile --fqbn esp32:esp32:nodemcu-32s ./esp32cam 
          arduino-cli compile --fqbn esp32:esp32:nodemcu-32s ./esp32cam/v2
